apiVersion: v1
kind: ImageStream
metadata:
  name: custom-jenkins
  labels:
    application: custom-jenkins
spec:
  tags:
    - name: latest
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  source:
    git:
      uri: https://github.com/sunming93/customized-jenkins.git
      ref: master
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.11.154-1
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest
